import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPhone, faEnvelope } from "@fortawesome/free-solid-svg-icons";

import H2 from "../components/elementComponents/h2";
import H6 from "../components/elementComponents/h6";
import P from "../components/elementComponents/p";
import SmallLine from "../components/elementComponents/smallLine";
import Button from "../components/elementComponents/button";
import Layout from "../components/layout";
import Card from "../components/card";
import SlideShow from "../components/slideShow";
import Form from "../components/form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - websidesign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Layout
        pageTitle="Home"
        header="op maat website of webshop gemaakt voor jouw bezoeker"
        imageSrc="home.jpg"
        altText="altText"
        description="De websites die wij maken zijn op maat gemaakt en speciaal ontworpen om je klanten op de juiste manier aan te spreken"
        nextPage="Onze services"
        nextPageUrl="/services"
      >
        <main>
          <div id="expertises" className="item relative container mx-auto px-4">
            <H2 addClass="text-blue w-auto text-center sm:text-left sm:ml-8 md:ml-16 xl:ml-36 2xl:ml-56">
              Services
            </H2>
            <Card
              addClass="sm:ml-8 md:ml-16 lg:float-left xl:ml-36 2xl:ml-56 mb-20 lg:mb-0"
              title="Website ontwikkelen"
              paragraph="Wij kunnen een website ontwerp maken, een ontwerp realiseren of een gehele website op maat maken"
              imageLink="/website-ontwikkelen.jpg"
            >
              <Button pageLink="/services/website-ontwikkelen">
                meer lezen
              </Button>
            </Card>
            <Card
              addClass="sm:mr-8 md:mr-16 sm:float-right lg:float-right lg:mr-16 lg:mt-24 xl:mr-36 2xl:float-right 2xl:mt-32 2xl:mr-56"
              title="Webshop ontwikkelen"
              paragraph="Wil je aan je bestaande website een shop toevoegen? of een hele
              nieuwe webshop?"
              imageLink="/webshop-ontwikkelen.jpg"
            >
              <Button pageLink="/services/webshop-ontwikkelen">
                meer lezen
              </Button>
            </Card>
            <div className="clear-both" />
          </div>
          <SlideShow />
          <div className="item container mx-auto px-4">
            <div className="max-w-sm mx-auto md:float-left md:mt-2 lg:ml-16 xl:ml-32 2xl:ml-64">
              <div className="flex items-center">
                <SmallLine addClass="bg-blue" />
                <H6 addClass="text-blue px-3">Ben je</H6>
                <SmallLine addClass="bg-blue" />
              </div>
              <H2 addClass="text-blue">Benieuwd naar de mogelijkheden?</H2>
              <P addClass="mb-10">Neem vrijblijvend contact met ons op.</P>
              <div className="float-left text-blue">
                <div className="mx-auto w-[2em] h-[2em]">
                  <FontAwesomeIcon icon={faPhone} size="2xl" />
                </div>
                <span className="block text-black mt-4">+31 6 363 588 63</span>
              </div>
              <div className="float-left ml-4 text-blue md:ml-8">
                <div className="mx-auto w-[2em] h-[2em]">
                  <FontAwesomeIcon icon={faEnvelope} size="2xl" />
                </div>
                <span className="block text-black mt-4">
                  service@websidesign.nl
                </span>
              </div>
              <div className="clear-both"></div>
            </div>
            <div className="mt-12 md:mt-0 md:float-right md:w-5/12 lg:mr-16 xl:w-5/12 xl:mr-32 2xl:w-4/12 2xl:mr-64">
              <Form />
            </div>
            <div className="clear-both"></div>
          </div>
        </main>
      </Layout>
    </>
  );
}
